import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import {
  Network,
  Search,
  ZoomIn,
  ZoomOut,
  Maximize2,
  Play,
  Pause,
  RotateCcw,
  Download,
  Filter,
  Layers,
  Code2,
  FileText,
  Boxes,
  Compass,
  ChevronRight,
  ExternalLink,
  Copy,
  Check,
  Sparkles,
  Info,
  X
} from 'lucide-react';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';

// Subsystem Color Mapping & Grouping
const SUBSYSTEM_CONFIG = {
  'React UI Components': {
    color: '#38BDF8', // Cyan/Sky Blue
    bg: 'rgba(56, 189, 248, 0.15)',
    border: 'rgba(56, 189, 248, 0.4)',
    icon: Boxes,
    match: (f) => f.includes('frontend/src/views') || f.includes('frontend/src/components')
  },
  'React State & Hooks': {
    color: '#818CF8', // Indigo
    bg: 'rgba(129, 140, 248, 0.15)',
    border: 'rgba(129, 140, 248, 0.4)',
    icon: Code2,
    match: (f) => f.includes('frontend/src') && !f.includes('views') && !f.includes('components')
  },
  'FastAPI REST Layer': {
    color: '#10B981', // Emerald
    bg: 'rgba(16, 185, 129, 0.15)',
    border: 'rgba(16, 185, 129, 0.4)',
    icon: Network,
    match: (f) => f.includes('backend/api') || f.includes('backend/main') || f.includes('backend/schemas') || f.includes('backend/security')
  },
  'ML & Hazard Models': {
    color: '#F59E0B', // Amber
    bg: 'rgba(245, 158, 11, 0.15)',
    border: 'rgba(245, 158, 11, 0.4)',
    icon: Sparkles,
    match: (f) => f.includes('backend/ml')
  },
  'Unified Ingestion': {
    color: '#06B6D4', // Teal/Cyan
    bg: 'rgba(6, 182, 212, 0.15)',
    border: 'rgba(6, 182, 212, 0.4)',
    icon: Compass,
    match: (f) => f.includes('backend/ingestion')
  },
  'Alerts & Translation': {
    color: '#EF4444', // Red/Coral
    bg: 'rgba(239, 68, 68, 0.15)',
    border: 'rgba(239, 68, 68, 0.4)',
    icon: Layers,
    match: (f) => f.includes('backend/alerts')
  },
  'PostgreSQL / PostGIS DB': {
    color: '#A855F7', // Purple
    bg: 'rgba(168, 85, 247, 0.15)',
    border: 'rgba(168, 85, 247, 0.4)',
    icon: FileText,
    match: (f) => f.includes('backend/models') || f.includes('backend/database') || f.includes('seed')
  },
  'Automated Tests': {
    color: '#EC4899', // Pink
    bg: 'rgba(236, 72, 153, 0.15)',
    border: 'rgba(236, 72, 153, 0.4)',
    icon: Code2,
    match: (f) => f.includes('tests')
  },
  'Native Android': {
    color: '#34D399', // Mint
    bg: 'rgba(52, 211, 153, 0.15)',
    border: 'rgba(52, 211, 153, 0.4)',
    icon: Boxes,
    match: (f) => f.includes('frontend/android')
  },
  'Core Config & Setup': {
    color: '#A1A1AA', // Zinc
    bg: 'rgba(161, 161, 170, 0.12)',
    border: 'rgba(161, 161, 170, 0.3)',
    icon: FileText,
    match: () => true
  }
};

function getSubsystem(file) {
  const f = (file || '').replace(/\\/g, '/').toLowerCase();
  for (const [key, cfg] of Object.entries(SUBSYSTEM_CONFIG)) {
    if (key !== 'Core Config & Setup' && cfg.match(f)) return key;
  }
  return 'Core Config & Setup';
}

export default function DevKnowledgeGraphView({ onNavigateSection }) {
  const canvasRef = useRef(null);

  // Data states
  const [rawGraph, setRawGraph] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [copiedPath, setCopiedPath] = useState(false);

  // Interactive controls
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedSubsystem, setSelectedSubsystem] = useState('all');
  const [minDegree, setMinDegree] = useState(2); // default filter small leaf nodes
  const [isPaused, setIsPaused] = useState(false);
  const [showLabels, setShowLabels] = useState(true);
  const [selectedNode, setSelectedNode] = useState(null);
  const [hoveredNode, setHoveredNode] = useState(null);

  // Camera Pan & Zoom
  const [zoom, setZoom] = useState(0.85);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const isDraggingCanvas = useRef(false);
  const dragStart = useRef({ x: 0, y: 0 });
  const draggedNode = useRef(null);

  // Load knowledge graph data generated by graphify
  useEffect(() => {
    setIsLoading(true);
    fetch('/data/graph.json')
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => {
        setRawGraph(data);
        setIsLoading(false);
      })
      .catch((err) => {
        console.warn('Could not load /data/graph.json, generating in-memory architecture graph', err);
        // Fallback architecture graph
        setRawGraph(createFallbackGraph());
        setIsLoading(false);
      });
  }, []);

  // Process nodes, calculate degrees and subsystems
  const processedData = useMemo(() => {
    if (!rawGraph || !rawGraph.nodes) return { nodes: [], links: [], godNodes: [], stats: {} };

    const nodeMap = new Map();
    const degreeMap = new Map();
    const inDegreeMap = new Map();
    const outDegreeMap = new Map();

    // Initialize degrees
    rawGraph.nodes.forEach((n) => {
      degreeMap.set(n.id, 0);
      inDegreeMap.set(n.id, []);
      outDegreeMap.set(n.id, []);
    });

    const links = (rawGraph.links || rawGraph.edges || []).map((l) => {
      const s = typeof l.source === 'object' ? l.source.id : l.source;
      const t = typeof l.target === 'object' ? l.target.id : l.target;

      degreeMap.set(s, (degreeMap.get(s) || 0) + 1);
      degreeMap.set(t, (degreeMap.get(t) || 0) + 1);

      if (outDegreeMap.has(s)) outDegreeMap.get(s).push({ target: t, relation: l.relation || 'references' });
      if (inDegreeMap.has(t)) inDegreeMap.get(t).push({ source: s, relation: l.relation || 'referenced_by' });

      return { source: s, target: t, relation: l.relation || 'references' };
    });

    const nodes = rawGraph.nodes.map((n, idx) => {
      const subsystem = getSubsystem(n.source_file);
      const degree = degreeMap.get(n.id) || 0;
      const angle = (idx / rawGraph.nodes.length) * 2 * Math.PI;
      const radius = 250 + Math.random() * 350;

      return {
        ...n,
        subsystem,
        degree,
        inbound: inDegreeMap.get(n.id) || [],
        outbound: outDegreeMap.get(n.id) || [],
        x: n.x || Math.cos(angle) * radius,
        y: n.y || Math.sin(angle) * radius,
        vx: 0,
        vy: 0,
        radius: Math.min(22, Math.max(5, Math.sqrt(degree + 1) * 3.5)),
        color: SUBSYSTEM_CONFIG[subsystem]?.color || '#A1A1AA'
      };
    });

    nodes.forEach((n) => nodeMap.set(n.id, n));

    // Valid links where both nodes exist
    const validLinks = links.filter((l) => nodeMap.has(l.source) && nodeMap.has(l.target));

    // God nodes (Top 10 highest degree)
    const sorted = [...nodes].sort((a, b) => b.degree - a.degree);
    const godNodes = sorted.slice(0, 10);

    return {
      nodes,
      links: validLinks,
      nodeMap,
      godNodes,
      stats: {
        totalNodes: nodes.length,
        totalLinks: validLinks.length,
        communities: new Set(nodes.map((n) => n.community)).size
      }
    };
  }, [rawGraph]);

  // Filtered nodes based on subsystem, degree threshold, and search
  const visibleData = useMemo(() => {
    if (!processedData.nodes) return { nodes: [], links: [] };

    const query = searchQuery.trim().toLowerCase();

    const filteredNodes = processedData.nodes.filter((n) => {
      if (selectedSubsystem !== 'all' && n.subsystem !== selectedSubsystem) return false;
      if (query) {
        const matchLabel = (n.label || '').toLowerCase().includes(query);
        const matchFile = (n.source_file || '').toLowerCase().includes(query);
        const matchId = (n.id || '').toLowerCase().includes(query);
        return matchLabel || matchFile || matchId;
      }
      return n.degree >= minDegree;
    });

    const visibleIds = new Set(filteredNodes.map((n) => n.id));
    const filteredLinks = processedData.links.filter(
      (l) => visibleIds.has(l.source) && visibleIds.has(l.target)
    );

    return { nodes: filteredNodes, links: filteredLinks, nodeMap: processedData.nodeMap };
  }, [processedData, selectedSubsystem, minDegree, searchQuery]);

  // Physics Force Simulation Loop
  const nodesRef = useRef([]);
  nodesRef.current = visibleData.nodes;
  const linksRef = useRef([]);
  linksRef.current = visibleData.links;

  useEffect(() => {
    if (!canvasRef.current || visibleData.nodes.length === 0) return;

    let animId;
    let alpha = 1.0;

    const tick = () => {
      const nodes = nodesRef.current;
      const links = linksRef.current;
      const nLen = nodes.length;

      if (!isPaused && alpha > 0.002) {
        // 1. Central Gravity
        for (let i = 0; i < nLen; i++) {
          const n = nodes[i];
          n.vx -= n.x * 0.0006 * alpha;
          n.vy -= n.y * 0.0006 * alpha;
        }

        // 2. Node-Node Repulsion (Cap distance for speed)
        for (let i = 0; i < nLen; i++) {
          const a = nodes[i];
          for (let j = i + 1; j < nLen; j++) {
            const b = nodes[j];
            const dx = b.x - a.x;
            const dy = b.y - a.y;
            const distSq = dx * dx + dy * dy + 40;
            if (distSq < 160000) {
              const dist = Math.sqrt(distSq);
              const force = (alpha * 1200) / distSq;
              const fx = (dx / dist) * force;
              const fy = (dy / dist) * force;
              a.vx -= fx;
              a.vy -= fy;
              b.vx += fx;
              b.vy += fy;
            }
          }
        }

        // 3. Link Spring Attraction
        for (let k = 0; k < links.length; k++) {
          const l = links[k];
          const a = typeof l.source === 'object' ? l.source : processedData.nodeMap?.get(l.source);
          const b = typeof l.target === 'object' ? l.target : processedData.nodeMap?.get(l.target);
          if (a && b) {
            const dx = b.x - a.x;
            const dy = b.y - a.y;
            const dist = Math.sqrt(dx * dx + dy * dy) || 1;
            const targetDist = 70;
            const force = (dist - targetDist) * 0.025 * alpha;
            const fx = (dx / dist) * force;
            const fy = (dy / dist) * force;
            a.vx += fx;
            a.vy += fy;
            b.vx -= fx;
            b.vy -= fy;
          }
        }

        // 4. Euler Integration & Damping
        for (let i = 0; i < nLen; i++) {
          const n = nodes[i];
          if (draggedNode.current === n) continue;
          n.vx *= 0.86;
          n.vy *= 0.86;
          n.x += n.vx;
          n.y += n.vy;
        }

        alpha *= 0.992;
      }

      // Render Canvas Frame
      draw();
      animId = requestAnimationFrame(tick);
    };

    const draw = () => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      const ctx = canvas.getContext('2d');
      const width = canvas.width;
      const height = canvas.height;

      ctx.clearRect(0, 0, width, height);

      // Background grid
      ctx.save();
      ctx.fillStyle = '#08080A';
      ctx.fillRect(0, 0, width, height);

      // Apply Pan & Zoom transformation
      ctx.translate(width / 2 + pan.x, height / 2 + pan.y);
      ctx.scale(zoom, zoom);

      // Grid dots
      ctx.fillStyle = 'rgba(255, 255, 255, 0.03)';
      const gridSize = 40;
      const minX = (-width / 2 - pan.x) / zoom;
      const maxX = (width / 2 - pan.x) / zoom;
      const minY = (-height / 2 - pan.y) / zoom;
      const maxY = (height / 2 - pan.y) / zoom;

      for (let x = Math.floor(minX / gridSize) * gridSize; x < maxX; x += gridSize) {
        for (let y = Math.floor(minY / gridSize) * gridSize; y < maxY; y += gridSize) {
          ctx.fillRect(x, y, 1.5, 1.5);
        }
      }

      const activeTarget = selectedNode || hoveredNode;
      const activeNeighborIds = new Set();
      if (activeTarget) {
        activeNeighborIds.add(activeTarget.id);
        activeTarget.inbound?.forEach((inb) => activeNeighborIds.add(inb.source));
        activeTarget.outbound?.forEach((outb) => activeNeighborIds.add(outb.target));
      }

      const nodes = nodesRef.current;
      const links = linksRef.current;

      // Draw Edges
      for (let k = 0; k < links.length; k++) {
        const l = links[k];
        const a = typeof l.source === 'object' ? l.source : processedData.nodeMap?.get(l.source);
        const b = typeof l.target === 'object' ? l.target : processedData.nodeMap?.get(l.target);
        if (!a || !b) continue;

        const isHighlighted =
          activeTarget &&
          (a.id === activeTarget.id || b.id === activeTarget.id);
        const isDimmed = activeTarget && !isHighlighted;

        ctx.beginPath();
        ctx.moveTo(a.x, a.y);
        ctx.lineTo(b.x, b.y);

        if (isHighlighted) {
          ctx.strokeStyle = '#38BDF8';
          ctx.lineWidth = 2.2 / zoom;
          ctx.globalAlpha = 0.85;
        } else if (isDimmed) {
          ctx.strokeStyle = 'rgba(255, 255, 255, 0.06)';
          ctx.lineWidth = 0.8 / zoom;
          ctx.globalAlpha = 0.15;
        } else {
          ctx.strokeStyle = 'rgba(255, 255, 255, 0.12)';
          ctx.lineWidth = 1 / zoom;
          ctx.globalAlpha = 0.35;
        }
        ctx.stroke();
      }

      ctx.globalAlpha = 1.0;

      // Draw Nodes
      for (let i = 0; i < nodes.length; i++) {
        const n = nodes[i];
        const isSelected = selectedNode?.id === n.id;
        const isHovered = hoveredNode?.id === n.id;
        const isNeighbor = activeTarget && activeNeighborIds.has(n.id);
        const isDimmed = activeTarget && !isNeighbor;

        ctx.save();
        ctx.translate(n.x, n.y);

        const r = n.radius || 8;

        // Dim non-neighbors
        if (isDimmed) {
          ctx.globalAlpha = 0.2;
        }

        // Halo for selected / hovered or God Nodes
        if (isSelected || isHovered || n.degree >= 15) {
          ctx.beginPath();
          ctx.arc(0, 0, r + 5, 0, Math.PI * 2);
          ctx.fillStyle = isSelected
            ? 'rgba(56, 189, 248, 0.3)'
            : isHovered
            ? 'rgba(255, 255, 255, 0.2)'
            : 'rgba(245, 158, 11, 0.2)';
          ctx.fill();
        }

        // Main Node Body
        ctx.beginPath();
        ctx.arc(0, 0, r, 0, Math.PI * 2);
        ctx.fillStyle = n.color || '#38BDF8';
        ctx.fill();

        ctx.lineWidth = isSelected ? 3 : 1.5;
        ctx.strokeStyle = isSelected ? '#FFFFFF' : 'rgba(0, 0, 0, 0.6)';
        ctx.stroke();

        // Node Label
        if (showLabels || isSelected || isHovered || n.degree >= 8) {
          const label = n.label || n.id;
          const fontSize = Math.max(10, Math.min(14, 11 / zoom));
          ctx.font = `${isSelected || isHovered ? '600' : '400'} ${fontSize}px Inter, sans-serif`;

          const textWidth = ctx.measureText(label).width;
          const pad = 4;
          const textY = r + fontSize + 2;

          // Capsule background
          ctx.fillStyle = 'rgba(10, 10, 12, 0.85)';
          ctx.fillRect(-textWidth / 2 - pad, textY - fontSize + 2, textWidth + pad * 2, fontSize + 2);

          ctx.fillStyle = isSelected ? '#38BDF8' : isHovered ? '#FFFFFF' : '#D1D5DB';
          ctx.textAlign = 'center';
          ctx.fillText(label, 0, textY);
        }

        ctx.restore();
      }

      ctx.restore();
    };

    animId = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(animId);
  }, [processedData, visibleData, isPaused, zoom, pan, selectedNode, hoveredNode, showLabels]);

  // Convert screen coords to canvas simulation coords
  const screenToWorld = useCallback(
    (screenX, screenY) => {
      const canvas = canvasRef.current;
      if (!canvas) return { x: 0, y: 0 };
      const rect = canvas.getBoundingClientRect();
      const clientX = screenX - rect.left;
      const clientY = screenY - rect.top;
      return {
        x: (clientX - canvas.width / 2 - pan.x) / zoom,
        y: (clientY - canvas.height / 2 - pan.y) / zoom
      };
    },
    [pan, zoom]
  );

  // Mouse / Canvas Event Handlers
  const handleMouseDown = (e) => {
    const { x, y } = screenToWorld(e.clientX, e.clientY);
    const nodes = visibleData.nodes;

    // Check if clicked on a node
    for (let i = nodes.length - 1; i >= 0; i--) {
      const n = nodes[i];
      const dx = n.x - x;
      const dy = n.y - y;
      if (dx * dx + dy * dy <= (n.radius + 6) * (n.radius + 6)) {
        draggedNode.current = n;
        setSelectedNode(n);
        return;
      }
    }

    // Otherwise pan canvas
    isDraggingCanvas.current = true;
    dragStart.current = { x: e.clientX - pan.x, y: e.clientY - pan.y };
  };

  const handleMouseMove = (e) => {
    if (draggedNode.current) {
      const { x, y } = screenToWorld(e.clientX, e.clientY);
      draggedNode.current.x = x;
      draggedNode.current.y = y;
      draggedNode.current.vx = 0;
      draggedNode.current.vy = 0;
      return;
    }

    if (isDraggingCanvas.current) {
      setPan({
        x: e.clientX - dragStart.current.x,
        y: e.clientY - dragStart.current.y
      });
      return;
    }

    // Hover detection
    const { x, y } = screenToWorld(e.clientX, e.clientY);
    const nodes = visibleData.nodes;
    let found = null;

    for (let i = nodes.length - 1; i >= 0; i--) {
      const n = nodes[i];
      const dx = n.x - x;
      const dy = n.y - y;
      if (dx * dx + dy * dy <= (n.radius + 6) * (n.radius + 6)) {
        found = n;
        break;
      }
    }
    setHoveredNode(found);
  };

  const handleMouseUp = () => {
    draggedNode.current = null;
    isDraggingCanvas.current = false;
  };

  const handleWheel = (e) => {
    e.preventDefault();
    const zoomFactor = e.deltaY < 0 ? 1.12 : 0.88;
    setZoom((z) => Math.max(0.15, Math.min(4.5, z * zoomFactor)));
  };

  // Center on a specific node
  const focusNode = (node) => {
    if (!node) return;
    setSelectedNode(node);
    setPan({ x: -node.x * zoom, y: -node.y * zoom });
  };

  const resetCamera = () => {
    setZoom(0.85);
    setPan({ x: 0, y: 0 });
  };

  const copySourcePath = (path) => {
    if (!path) return;
    navigator.clipboard.writeText(path);
    setCopiedPath(true);
    setTimeout(() => setCopiedPath(false), 1800);
  };

  // Export PNG snapshot
  const handleExportPNG = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const a = document.createElement('a');
    a.download = 'drishti-ai-knowledge-graph.png';
    a.href = canvas.toDataURL('image/png');
    a.click();
  };

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: 'calc(100vh - var(--header-height, 60px))',
        backgroundColor: '#08080A',
        color: '#F5F5F5',
        overflow: 'hidden',
        position: 'relative'
      }}
    >
      {/* 1. Header Toolbar */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '10px 18px',
          borderBottom: '1px solid var(--border-primary, #252525)',
          backgroundColor: 'rgba(10, 10, 12, 0.95)',
          backdropFilter: 'blur(16px)',
          zIndex: 10,
          flexWrap: 'wrap',
          gap: 12
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div
            style={{
              width: 34,
              height: 34,
              borderRadius: 8,
              backgroundColor: 'rgba(56, 189, 248, 0.12)',
              border: '1px solid rgba(56, 189, 248, 0.3)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#38BDF8'
            }}
          >
            <Network size={18} />
          </div>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <h1 style={{ margin: 0, fontSize: '1rem', fontWeight: 600, letterSpacing: '-0.01em' }}>
                Architecture Knowledge Graph
              </h1>
              <span
                style={{
                  fontSize: '0.68rem',
                  padding: '1px 6px',
                  borderRadius: 9999,
                  backgroundColor: 'rgba(245, 158, 11, 0.15)',
                  color: '#F59E0B',
                  border: '1px solid rgba(245, 158, 11, 0.35)',
                  fontWeight: 600
                }}
              >
                DEVELOPER AST
              </span>
            </div>
            <p style={{ margin: 0, fontSize: '0.74rem', color: 'var(--text-secondary, #A1A1AA)' }}>
              Built with Graphify & React · {processedData.stats.totalNodes || 0} nodes ·{' '}
              {processedData.stats.totalLinks || 0} edges · {processedData.stats.communities || 0} clusters
            </p>
          </div>
        </div>

        {/* Search & Quick Controls */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          {/* Search Box */}
          <div
            style={{
              position: 'relative',
              display: 'flex',
              alignItems: 'center',
              backgroundColor: '#121215',
              borderRadius: 6,
              border: '1px solid #282830',
              padding: '4px 10px',
              width: 220
            }}
          >
            <Search size={14} style={{ color: '#71717A', marginRight: 6 }} />
            <input
              type="text"
              placeholder="Search symbols, routes, views..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={{
                background: 'none',
                border: 'none',
                outline: 'none',
                color: '#F5F5F5',
                fontSize: '0.78rem',
                width: '100%'
              }}
            />
            {searchQuery && (
              <button
                type="button"
                onClick={() => setSearchQuery('')}
                style={{ background: 'none', border: 'none', color: '#71717A', cursor: 'pointer', padding: 0 }}
              >
                <X size={12} />
              </button>
            )}
          </div>

          {/* Min Degree Filter */}
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              fontSize: '0.74rem',
              color: '#A1A1AA',
              background: '#121215',
              padding: '4px 10px',
              borderRadius: 6,
              border: '1px solid #282830'
            }}
          >
            <span>Min Connections:</span>
            <input
              type="range"
              min={1}
              max={15}
              value={minDegree}
              onChange={(e) => setMinDegree(Number(e.target.value))}
              style={{ width: 65, cursor: 'pointer', accentColor: '#38BDF8' }}
              title={`Show nodes with at least ${minDegree} dependencies`}
            />
            <span style={{ fontWeight: 600, color: '#38BDF8', minWidth: 16 }}>{minDegree}</span>
          </div>

          {/* Physics Play/Pause */}
          <button
            type="button"
            onClick={() => setIsPaused((p) => !p)}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 4,
              padding: '5px 9px',
              fontSize: '0.74rem',
              borderRadius: 6,
              backgroundColor: isPaused ? 'rgba(245, 158, 11, 0.15)' : '#121215',
              color: isPaused ? '#F59E0B' : '#D1D5DB',
              border: `1px solid ${isPaused ? 'rgba(245, 158, 11, 0.35)' : '#282830'}`,
              cursor: 'pointer'
            }}
          >
            {isPaused ? <Play size={13} /> : <Pause size={13} />}
            <span>{isPaused ? 'Resume Physics' : 'Pause Physics'}</span>
          </button>

          {/* Zoom In / Out / Reset */}
          <div style={{ display: 'flex', background: '#121215', borderRadius: 6, border: '1px solid #282830' }}>
            <button
              type="button"
              onClick={() => setZoom((z) => Math.min(4.5, z * 1.2))}
              style={{ background: 'none', border: 'none', color: '#D1D5DB', padding: '5px 8px', cursor: 'pointer' }}
              title="Zoom In"
            >
              <ZoomIn size={14} />
            </button>
            <button
              type="button"
              onClick={() => setZoom((z) => Math.max(0.15, z * 0.8))}
              style={{ background: 'none', border: 'none', color: '#D1D5DB', padding: '5px 8px', cursor: 'pointer', borderLeft: '1px solid #282830' }}
              title="Zoom Out"
            >
              <ZoomOut size={14} />
            </button>
            <button
              type="button"
              onClick={resetCamera}
              style={{ background: 'none', border: 'none', color: '#D1D5DB', padding: '5px 8px', cursor: 'pointer', borderLeft: '1px solid #282830' }}
              title="Center View"
            >
              <RotateCcw size={14} />
            </button>
          </div>

          {/* Export PNG */}
          <button
            type="button"
            onClick={handleExportPNG}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 5,
              padding: '5px 9px',
              fontSize: '0.74rem',
              borderRadius: 6,
              backgroundColor: '#121215',
              color: '#D1D5DB',
              border: '1px solid #282830',
              cursor: 'pointer'
            }}
            title="Download high-res PNG image of graph"
          >
            <Download size={13} />
            <span>Export PNG</span>
          </button>
        </div>
      </div>

      {/* 2. Subsystem Domain Pill Filters */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 6,
          padding: '6px 18px',
          backgroundColor: '#0C0C0E',
          borderBottom: '1px solid #1C1C22',
          overflowX: 'auto',
          whiteSpace: 'nowrap',
          zIndex: 9
        }}
      >
        <span style={{ fontSize: '0.68rem', fontWeight: 600, color: '#71717A', textTransform: 'uppercase', marginRight: 4 }}>
          Subsystems:
        </span>
        <button
          type="button"
          onClick={() => setSelectedSubsystem('all')}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 4,
            padding: '3px 9px',
            borderRadius: 9999,
            fontSize: '0.72rem',
            fontWeight: 500,
            cursor: 'pointer',
            border: `1px solid ${selectedSubsystem === 'all' ? '#38BDF8' : '#282830'}`,
            backgroundColor: selectedSubsystem === 'all' ? 'rgba(56, 189, 248, 0.15)' : '#141418',
            color: selectedSubsystem === 'all' ? '#38BDF8' : '#A1A1AA'
          }}
        >
          All ({processedData.nodes.length})
        </button>

        {Object.entries(SUBSYSTEM_CONFIG).map(([name, cfg]) => {
          const isSel = selectedSubsystem === name;
          const count = processedData.nodes.filter((n) => n.subsystem === name).length;
          if (count === 0) return null;

          return (
            <button
              key={name}
              type="button"
              onClick={() => setSelectedSubsystem(name)}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 5,
                padding: '3px 9px',
                borderRadius: 9999,
                fontSize: '0.72rem',
                fontWeight: 500,
                cursor: 'pointer',
                border: `1px solid ${isSel ? cfg.color : '#282830'}`,
                backgroundColor: isSel ? cfg.bg : '#141418',
                color: isSel ? cfg.color : '#A1A1AA',
                transition: 'all 0.15s ease'
              }}
            >
              <span
                style={{
                  width: 6,
                  height: 6,
                  borderRadius: '50%',
                  backgroundColor: cfg.color
                }}
              />
              <span>{name}</span>
              <span style={{ opacity: 0.6, fontSize: '0.65rem' }}>({count})</span>
            </button>
          );
        })}
      </div>

      {/* 3. Main Canvas & Split Inspector Workspace */}
      <div style={{ flex: 1, display: 'flex', position: 'relative', overflow: 'hidden' }}>
        {/* Fullscreen Interactive Canvas */}
        <canvas
          ref={canvasRef}
          width={typeof window !== 'undefined' ? window.innerWidth : 1400}
          height={typeof window !== 'undefined' ? window.innerHeight - 130 : 800}
          onMouseDown={handleMouseDown}
          onMouseMove={handleMouseMove}
          onMouseUp={handleMouseUp}
          onWheel={handleWheel}
          style={{
            width: '100%',
            height: '100%',
            cursor: draggedNode.current ? 'grabbing' : hoveredNode ? 'pointer' : 'grab',
            display: 'block'
          }}
        />

        {/* Bottom Left HUD: Active Visible Stats */}
        <div
          style={{
            position: 'absolute',
            bottom: 14,
            left: 18,
            backgroundColor: 'rgba(12, 12, 16, 0.88)',
            backdropFilter: 'blur(12px)',
            border: '1px solid #252530',
            borderRadius: 8,
            padding: '8px 12px',
            fontSize: '0.72rem',
            color: '#A1A1AA',
            display: 'flex',
            alignItems: 'center',
            gap: 16,
            zIndex: 8,
            pointerEvents: 'none'
          }}
        >
          <div>
            Visible Nodes: <span style={{ color: '#38BDF8', fontWeight: 600 }}>{visibleData.nodes.length}</span>
          </div>
          <div>
            Active Edges: <span style={{ color: '#10B981', fontWeight: 600 }}>{visibleData.links.length}</span>
          </div>
          <div>
            Zoom: <span style={{ color: '#F59E0B', fontWeight: 600 }}>{Math.round(zoom * 100)}%</span>
          </div>
          <div style={{ color: '#71717A' }}>
            Tip: Scroll to zoom · Drag canvas to pan · Drag node to reposition
          </div>
        </div>

        {/* Right-Side Node Inspector Drawer */}
        <div
          style={{
            width: 360,
            backgroundColor: 'rgba(13, 13, 16, 0.96)',
            backdropFilter: 'blur(24px)',
            borderLeft: '1px solid var(--border-primary, #252525)',
            display: 'flex',
            flexDirection: 'column',
            overflowY: 'auto',
            zIndex: 9,
            position: 'relative',
            boxShadow: '-8px 0 24px rgba(0, 0, 0, 0.5)'
          }}
        >
          {selectedNode ? (
            <div style={{ padding: '16px 18px', display: 'flex', flexDirection: 'column', gap: 14 }}>
              {/* Node Title Lockup */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <span
                    style={{
                      fontSize: '0.68rem',
                      fontWeight: 600,
                      padding: '2px 8px',
                      borderRadius: 4,
                      backgroundColor: SUBSYSTEM_CONFIG[selectedNode.subsystem]?.bg || '#1F2937',
                      color: SUBSYSTEM_CONFIG[selectedNode.subsystem]?.color || '#38BDF8',
                      border: `1px solid ${SUBSYSTEM_CONFIG[selectedNode.subsystem]?.border || '#374151'}`
                    }}
                  >
                    {selectedNode.subsystem}
                  </span>
                  <button
                    type="button"
                    onClick={() => setSelectedNode(null)}
                    style={{ background: 'none', border: 'none', color: '#71717A', cursor: 'pointer', padding: 2 }}
                    aria-label="Close Inspector"
                  >
                    <X size={16} />
                  </button>
                </div>
                <h3 style={{ margin: '8px 0 4px 0', fontSize: '1.05rem', fontWeight: 600, wordBreak: 'break-word' }}>
                  {selectedNode.label || selectedNode.id}
                </h3>
                <div style={{ fontSize: '0.72rem', color: '#71717A', fontFamily: 'JetBrains Mono, monospace' }}>
                  ID: {selectedNode.id}
                </div>
              </div>

              {/* Source File Location */}
              {selectedNode.source_file && (
                <div
                  style={{
                    backgroundColor: '#15151B',
                    border: '1px solid #282834',
                    borderRadius: 6,
                    padding: '8px 10px',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: 4
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span style={{ fontSize: '0.68rem', color: '#A1A1AA', fontWeight: 500 }}>SOURCE FILE</span>
                    <button
                      type="button"
                      onClick={() => copySourcePath(selectedNode.source_file)}
                      style={{
                        background: 'none',
                        border: 'none',
                        color: copiedPath ? '#10B981' : '#71717A',
                        cursor: 'pointer',
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: 3,
                        fontSize: '0.68rem'
                      }}
                      title="Copy file path"
                    >
                      {copiedPath ? <Check size={11} /> : <Copy size={11} />}
                      <span>{copiedPath ? 'Copied' : 'Copy'}</span>
                    </button>
                  </div>
                  <div
                    style={{
                      fontFamily: 'JetBrains Mono, monospace',
                      fontSize: '0.74rem',
                      color: '#E2E8F0',
                      wordBreak: 'break-all'
                    }}
                  >
                    {selectedNode.source_file}
                    {selectedNode.source_location ? `:${selectedNode.source_location}` : ''}
                  </div>
                </div>
              )}

              {/* Degree Metrics Cards */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>
                <div
                  style={{
                    backgroundColor: '#15151B',
                    border: '1px solid #282834',
                    borderRadius: 6,
                    padding: '8px',
                    textAlign: 'center'
                  }}
                >
                  <div style={{ fontSize: '0.68rem', color: '#71717A' }}>TOTAL DEPS</div>
                  <div style={{ fontSize: '1.1rem', fontWeight: 700, color: '#38BDF8', marginTop: 2 }}>
                    {selectedNode.degree}
                  </div>
                </div>
                <div
                  style={{
                    backgroundColor: '#15151B',
                    border: '1px solid #282834',
                    borderRadius: 6,
                    padding: '8px',
                    textAlign: 'center'
                  }}
                >
                  <div style={{ fontSize: '0.68rem', color: '#71717A' }}>INBOUND</div>
                  <div style={{ fontSize: '1.1rem', fontWeight: 700, color: '#10B981', marginTop: 2 }}>
                    {selectedNode.inbound?.length || 0}
                  </div>
                </div>
                <div
                  style={{
                    backgroundColor: '#15151B',
                    border: '1px solid #282834',
                    borderRadius: 6,
                    padding: '8px',
                    textAlign: 'center'
                  }}
                >
                  <div style={{ fontSize: '0.68rem', color: '#71717A' }}>OUTBOUND</div>
                  <div style={{ fontSize: '1.1rem', fontWeight: 700, color: '#F59E0B', marginTop: 2 }}>
                    {selectedNode.outbound?.length || 0}
                  </div>
                </div>
              </div>

              {/* Inbound Connections (What calls/uses this) */}
              <div>
                <div style={{ fontSize: '0.72rem', fontWeight: 600, color: '#A1A1AA', marginBottom: 6, textTransform: 'uppercase' }}>
                  Inbound References ({selectedNode.inbound?.length || 0})
                </div>
                {selectedNode.inbound?.length > 0 ? (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 4, maxHeight: 180, overflowY: 'auto' }}>
                    {selectedNode.inbound.map((inb, i) => {
                      const srcNode = processedData.nodeMap?.get(inb.source);
                      return (
                        <button
                          key={i}
                          type="button"
                          onClick={() => focusNode(srcNode)}
                          style={{
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'space-between',
                            backgroundColor: '#14141A',
                            border: '1px solid #242430',
                            borderRadius: 6,
                            padding: '6px 8px',
                            textAlign: 'left',
                            cursor: 'pointer',
                            color: '#F5F5F5',
                            fontSize: '0.74rem'
                          }}
                        >
                          <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                            {srcNode?.label || inb.source}
                          </span>
                          <span style={{ fontSize: '0.65rem', color: '#10B981', opacity: 0.8 }}>jump →</span>
                        </button>
                      );
                    })}
                  </div>
                ) : (
                  <div style={{ fontSize: '0.72rem', color: '#71717A', fontStyle: 'italic' }}>
                    No incoming connections found
                  </div>
                )}
              </div>

              {/* Outbound Connections (What this calls/uses) */}
              <div>
                <div style={{ fontSize: '0.72rem', fontWeight: 600, color: '#A1A1AA', marginBottom: 6, textTransform: 'uppercase' }}>
                  Outbound Dependencies ({selectedNode.outbound?.length || 0})
                </div>
                {selectedNode.outbound?.length > 0 ? (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 4, maxHeight: 180, overflowY: 'auto' }}>
                    {selectedNode.outbound.map((outb, i) => {
                      const tgtNode = processedData.nodeMap?.get(outb.target);
                      return (
                        <button
                          key={i}
                          type="button"
                          onClick={() => focusNode(tgtNode)}
                          style={{
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'space-between',
                            backgroundColor: '#14141A',
                            border: '1px solid #242430',
                            borderRadius: 6,
                            padding: '6px 8px',
                            textAlign: 'left',
                            cursor: 'pointer',
                            color: '#F5F5F5',
                            fontSize: '0.74rem'
                          }}
                        >
                          <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                            {tgtNode?.label || outb.target}
                          </span>
                          <span style={{ fontSize: '0.65rem', color: '#F59E0B', opacity: 0.8 }}>jump →</span>
                        </button>
                      );
                    })}
                  </div>
                ) : (
                  <div style={{ fontSize: '0.72rem', color: '#71717A', fontStyle: 'italic' }}>
                    No outgoing connections found
                  </div>
                )}
              </div>
            </div>
          ) : (
            /* Default: System Overview & God Nodes */
            <div style={{ padding: '16px 18px', display: 'flex', flexDirection: 'column', gap: 16 }}>
              <div>
                <h3 style={{ margin: '0 0 4px 0', fontSize: '0.95rem', fontWeight: 600 }}>
                  System Architecture Hub
                </h3>
                <p style={{ margin: 0, fontSize: '0.74rem', color: '#A1A1AA' }}>
                  Click any node in the canvas to inspect its source code, AST symbols, and cross-module dependencies.
                </p>
              </div>

              {/* God Nodes Leaderboard */}
              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>
                  <Sparkles size={14} style={{ color: '#F59E0B' }} />
                  <span style={{ fontSize: '0.72rem', fontWeight: 600, color: '#A1A1AA', textTransform: 'uppercase' }}>
                    Top Centrality God Nodes
                  </span>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
                  {processedData.godNodes.map((gn, idx) => (
                    <button
                      key={gn.id}
                      type="button"
                      onClick={() => focusNode(gn)}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        padding: '6px 10px',
                        backgroundColor: '#141419',
                        border: '1px solid #252530',
                        borderRadius: 6,
                        cursor: 'pointer',
                        textAlign: 'left'
                      }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8, overflow: 'hidden' }}>
                        <span style={{ fontSize: '0.68rem', color: '#F59E0B', fontWeight: 700, minWidth: 14 }}>
                          #{idx + 1}
                        </span>
                        <div style={{ overflow: 'hidden' }}>
                          <div style={{ fontSize: '0.76rem', color: '#F5F5F5', fontWeight: 600, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                            {gn.label || gn.id}
                          </div>
                          <div style={{ fontSize: '0.66rem', color: '#71717A', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                            {gn.source_file || 'system'}
                          </div>
                        </div>
                      </div>
                      <span
                        style={{
                          fontSize: '0.68rem',
                          fontWeight: 700,
                          color: '#38BDF8',
                          padding: '1px 6px',
                          borderRadius: 9999,
                          backgroundColor: 'rgba(56, 189, 248, 0.1)'
                        }}
                      >
                        {gn.degree}
                      </span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Subsystem Distribution */}
              <div>
                <span style={{ fontSize: '0.72rem', fontWeight: 600, color: '#A1A1AA', textTransform: 'uppercase', display: 'block', marginBottom: 8 }}>
                  Subsystem Distribution
                </span>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {Object.entries(SUBSYSTEM_CONFIG).map(([subName, cfg]) => {
                    const count = processedData.nodes.filter((n) => n.subsystem === subName).length;
                    if (count === 0) return null;
                    const pct = Math.round((count / (processedData.nodes.length || 1)) * 100);

                    return (
                      <div key={subName}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.7rem', color: '#D1D5DB', marginBottom: 2 }}>
                          <span>{subName}</span>
                          <span style={{ color: cfg.color, fontWeight: 600 }}>
                            {count} ({pct}%)
                          </span>
                        </div>
                        <div style={{ width: '100%', height: 4, backgroundColor: '#1E1E24', borderRadius: 2, overflow: 'hidden' }}>
                          <div
                            style={{
                              width: `${pct}%`,
                              height: '100%',
                              backgroundColor: cfg.color,
                              borderRadius: 2
                            }}
                          />
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// Fallback in-memory core architecture graph if JSON is unavailable
function createFallbackGraph() {
  const nodes = [
    { id: 'app_jsx', label: 'App.jsx', source_file: 'frontend/src/App.jsx', community: 1 },
    { id: 'dashboard_view', label: 'DashboardView.jsx', source_file: 'frontend/src/views/DashboardView.jsx', community: 1 },
    { id: 'risk_map', label: 'RiskMap.jsx', source_file: 'frontend/src/components/RiskMap.jsx', community: 1 },
    { id: 'zone_intelligence', label: 'ZoneIntelligence.jsx', source_file: 'frontend/src/components/ZoneIntelligence.jsx', community: 1 },
    { id: 'api_client', label: 'api.js', source_file: 'frontend/src/api.js', community: 2 },
    { id: 'field_report_form', label: 'FieldReportForm.jsx', source_file: 'frontend/src/components/FieldReportForm.jsx', community: 1 },
    { id: 'fastapi_main', label: 'main.py', source_file: 'backend/main.py', community: 3 },
    { id: 'routes_risk', label: 'routes_risk.py', source_file: 'backend/api/routes_risk.py', community: 3 },
    { id: 'routes_sos', label: 'routes_sos.py', source_file: 'backend/api/routes_sos.py', community: 3 },
    { id: 'routes_ingestion', label: 'routes_ingestion.py', source_file: 'backend/api/routes_ingestion.py', community: 3 },
    { id: 'ml_model', label: 'LandslideRiskModel', source_file: 'backend/ml/model.py', community: 4 },
    { id: 'ml_features', label: 'extract_features', source_file: 'backend/ml/features.py', community: 4 },
    { id: 'ingestion_pipeline', label: 'UnifiedIngestionPipeline', source_file: 'backend/ingestion/pipeline.py', community: 5 },
    { id: 'weather_service', label: 'WeatherIngestionService', source_file: 'backend/ingestion/weather.py', community: 5 },
    { id: 'imd_service', label: 'IMDIngestionService', source_file: 'backend/ingestion/imd.py', community: 5 },
    { id: 'terrain_service', label: 'TerrainIngestionService', source_file: 'backend/ingestion/terrain.py', community: 5 },
    { id: 'osm_service', label: 'OSMIngestionService', source_file: 'backend/ingestion/osm.py', community: 5 },
    { id: 'alert_engine', label: 'AlertEngine', source_file: 'backend/alerts/engine.py', community: 6 },
    { id: 'sms_service', label: 'Fast2SMSClient', source_file: 'backend/alerts/sms.py', community: 6 },
    { id: 'push_service', label: 'FCMClient', source_file: 'backend/alerts/push.py', community: 6 },
    { id: 'translate_service', label: 'TranslationService', source_file: 'backend/alerts/translate.py', community: 6 },
    { id: 'db_models', label: 'SQLAlchemy Models', source_file: 'backend/models.py', community: 7 },
    { id: 'db_conn', label: 'PostgresEngine', source_file: 'backend/database.py', community: 7 },
    { id: 'evac_graph', label: 'EvacuationGraph', source_file: 'backend/api/routes_dijkstra.py', community: 7 }
  ];

  const links = [
    { source: 'app_jsx', target: 'dashboard_view' },
    { source: 'app_jsx', target: 'api_client' },
    { source: 'dashboard_view', target: 'risk_map' },
    { source: 'dashboard_view', target: 'zone_intelligence' },
    { source: 'dashboard_view', target: 'api_client' },
    { source: 'field_report_form', target: 'api_client' },
    { source: 'api_client', target: 'fastapi_main' },
    { source: 'fastapi_main', target: 'routes_risk' },
    { source: 'fastapi_main', target: 'routes_sos' },
    { source: 'fastapi_main', target: 'routes_ingestion' },
    { source: 'routes_risk', target: 'ml_model' },
    { source: 'ml_model', target: 'ml_features' },
    { source: 'routes_ingestion', target: 'ingestion_pipeline' },
    { source: 'ingestion_pipeline', target: 'weather_service' },
    { source: 'ingestion_pipeline', target: 'imd_service' },
    { source: 'ingestion_pipeline', target: 'terrain_service' },
    { source: 'ingestion_pipeline', target: 'osm_service' },
    { source: 'ingestion_pipeline', target: 'translate_service' },
    { source: 'routes_sos', target: 'alert_engine' },
    { source: 'alert_engine', target: 'sms_service' },
    { source: 'alert_engine', target: 'push_service' },
    { source: 'alert_engine', target: 'translate_service' },
    { source: 'routes_risk', target: 'db_models' },
    { source: 'db_models', target: 'db_conn' },
    { source: 'evac_graph', target: 'db_models' }
  ];

  return { nodes, links };
}
